/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_PIEZO.h>
#include <Clock_PWM_PIEZO.h>
#include <Pin_1_1_Piezo.h>
#include <Pin_1_1_Piezo_aliases.h>
#include <LPComp_movement_detector.h>
#include <isr_LPComparator.h>
#include <Pin_positive_comparator.h>
#include <Pin_positive_comparator_aliases.h>
#include <Pin_negative_comparator.h>
#include <Pin_negative_comparator_aliases.h>
#include <Pin_P0_7_switch.h>
#include <Pin_P0_7_switch_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

